# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# 🔑 Login to Azure using the service connection
- task: AzureCLI@2
  inputs:
    azureSubscription: 'alpha-acr-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Azure login successful"

# 🐳 Pull a Docker image using Docker CLI
- task: Docker@2
  displayName: 'Pull Docker image'
  inputs:
    containerRegistry: 'uipathsvcalpwegeneralacr'
    command: 'login'

- script: |
    docker pull uipathsvcalpwegeneralacr.azurecr.io/sre/incident-management-middleware:v1.1.6.alpha
  displayName: 'Docker Pull Image'